apiVersion: v1
data:
  init.sql: |-
    CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        login VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        position VARCHAR(255),
    );
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres-cm1
